service: get-mensa-data

provider:
  name: aws
  runtime: nodejs6.10
  role: arn:aws:iam::555419802183:role/service-role/getMensaData

functions:
  cron:
    handler: handler.run
    events:
      - schedule: cron(0/15 5,6,7,8 ? * MON-FRI *)